apiVersion: v1
kind: Service
metadata:
  name: header-echo-service
spec:
  selector:
    app: header-echo-service
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-echo-service
spec:
  selector:
    matchLabels:
      app: header-echo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: header-echo-service
    spec:
      containers:
      - name: flask
        image: gunnarsolo/header-echo-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
